export const FETCH_PHOTOS_PENDING = 'FETCH_PHOTOS_PENDING';
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';
export const FETCH_PHOTOS_ERROR = 'FETCH_PHOTOS_ERROR';
export const CHANGE_FILTER = 'CHANGE_FILTER';

export const SINGLE_PHOTO_PENDING = 'SINGLE_PHOTO_PENDING';
export const SINGLE_PHOTO_SUCCESS = 'SINGLE_PHOTO_SUCCESS';
export const SINGLE_PHOTO_ERROR = 'SINGLE_PHOTO_ERROR';

export const FETCH_TOPICS_PENDING = 'FETCH_TOPICS_PENDING';
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_ERROR = 'FETCH_TOPICS_ERROR';
